version: '3.7'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=qwerty123
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DATABASE=ms_localization

volumes:
  postgresql_data:
    driver: local
